#!/bin/bash

if loc="$(type -p "clang-format")" && [[ -x $loc ]]; then
    for name in $(git diff --cached --name-only --diff-filter=ACM); do
        if echo $name | grep -Eq "\.[ch]$"; then
            echo "Formatting ${name}..."
            clang-format -i -style=file $name
        fi
    done
else
    echo "clang-format is not installed"
fi
